NAME: KAGGLE_NETHERLANDS
TARGET: rent
NUM:
  - ID: __ignored__
CATS:
  - ID: city
    TYPE: HASHING
    BITS: 32
  - ID: matchAge
    TYPE: HASHING
    BITS: 32
  - ID: roommates
    TYPE: HASHING
  - ID: energyLabel
    TYPE: HASHING
  - ID: matchCapacity
    TYPE: HASHING
#  - ID: descriptionTranslated
#    TYPE: BINARY_KEYS
#    KEYS: [["cheap", "expensive"]]

OUTLIERS: # (x,y)
  - ID: areaSqm
    INTERVAL: [0, 75]

OUTLIER_OCCURANCES: ["city", "matchAge"]
OUTLIER_THRESHOLD: 100

EXCLUDE: ["id","title","postalCode","descriptionNonTranslated","descriptionTranslated", "latitude", "longitude","firstSeenAt",
          "postedAgo", "rawAvailability","kitchen",
          "descriptionNonTranslated","matchLanguages",
          "coverImageUrl", "lastSeenAt"]  # matchStatus ??
EXCLUDE_AXIS: 1
